services:
  jenkins:
    container_name: jenkins
    build:
      context: ../..
      dockerfile: docker/jenkins/Dockerfile
    image: mondejarmarron18/jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
