services:
  app:
    container_name: jenkins-app-dev
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    image: mondejarmarron18/jenkins-app:dev
    environment:
      - PORT=5000
    env_file:
      - ../../.env.dev
    ports:
      - "5000:5000"
    volumes:
      - ../../:/app
      - /app/node_modules
